const apiData = {
  statusCode: 0,
  data: {
    cacheExpiryTime: 320,
    pages: 1,
    pageIndex: 0,
    scrubber: 0,
    filters: [
      {
        type: "FilterWidget",
        title: "Cuisines",
        key: "CUISINES",
        configType: "checkbox",
        visible: 1,
        options: [
          {
            option: "American",
            selected: 0,
            visible: 1,
          },
          {
            option: "Andhra",
            selected: 0,
            visible: 1,
          },
          {
            option: "Arabian",
            selected: 0,
            visible: 1,
          },
          {
            option: "Asian",
            selected: 0,
            visible: 1,
          },
          {
            option: "Assamese",
            selected: 0,
            visible: 1,
          },
          {
            option: "Awadhi",
            selected: 0,
            visible: 1,
          },
          {
            option: "Bakery",
            selected: 0,
            visible: 1,
          },
          {
            option: "Barbecue",
            selected: 0,
            visible: 1,
          },
          {
            option: "Bengali",
            selected: 0,
            visible: 1,
          },
          {
            option: "Beverages",
            selected: 0,
            visible: 1,
          },
          {
            option: "Biryani",
            selected: 0,
            visible: 1,
          },
          {
            option: "British",
            selected: 0,
            visible: 1,
          },
          {
            option: "Buffalo meat",
            selected: 0,
            visible: 1,
          },
          {
            option: "Burgers",
            selected: 0,
            visible: 1,
          },
          {
            option: "Burmese",
            selected: 0,
            visible: 1,
          },
          {
            option: "Cafe",
            selected: 0,
            visible: 1,
          },
          {
            option: "Chaat",
            selected: 0,
            visible: 1,
          },
          {
            option: "Chettinad",
            selected: 0,
            visible: 1,
          },
          {
            option: "Chinese",
            selected: 0,
            visible: 1,
          },
          {
            option: "Coastal",
            selected: 0,
            visible: 1,
          },
          {
            option: "Combo",
            selected: 0,
            visible: 1,
          },
          {
            option: "Continental",
            selected: 0,
            visible: 1,
          },
          {
            option: "Desserts",
            selected: 0,
            visible: 1,
          },
          {
            option: "European",
            selected: 0,
            visible: 1,
          },
          {
            option: "Fast Food",
            selected: 0,
            visible: 1,
          },
          {
            option: "French",
            selected: 0,
            visible: 1,
          },
          {
            option: "Goan",
            selected: 0,
            visible: 1,
          },
          {
            option: "Greek",
            selected: 0,
            visible: 1,
          },
          {
            option: "Grill",
            selected: 0,
            visible: 1,
          },
          {
            option: "Gujarati",
            selected: 0,
            visible: 1,
          },
          {
            option: "Healthy Food",
            selected: 0,
            visible: 1,
          },
          {
            option: "Home Food",
            selected: 0,
            visible: 1,
          },
          {
            option: "Hyderabadi",
            selected: 0,
            visible: 1,
          },
          {
            option: "Ice Cream",
            selected: 0,
            visible: 1,
          },
          {
            option: "Ice Cream Cakes",
            selected: 0,
            visible: 1,
          },
          {
            option: "Indian",
            selected: 0,
            visible: 1,
          },
          {
            option: "Indonesian",
            selected: 0,
            visible: 1,
          },
          {
            option: "Italian",
            selected: 0,
            visible: 1,
          },
          {
            option: "Italian-American",
            selected: 0,
            visible: 1,
          },
          {
            option: "Jain",
            selected: 0,
            visible: 1,
          },
          {
            option: "Japanese",
            selected: 0,
            visible: 1,
          },
          {
            option: "Juices",
            selected: 0,
            visible: 1,
          },
          {
            option: "Kebabs",
            selected: 0,
            visible: 1,
          },
          {
            option: "Kerala",
            selected: 0,
            visible: 1,
          },
          {
            option: "Keto",
            selected: 0,
            visible: 1,
          },
          {
            option: "Konkan",
            selected: 0,
            visible: 1,
          },
          {
            option: "Korean",
            selected: 0,
            visible: 1,
          },
          {
            option: "Lebanese",
            selected: 0,
            visible: 1,
          },
          {
            option: "Lucknowi",
            selected: 0,
            visible: 1,
          },
          {
            option: "Maharashtrian",
            selected: 0,
            visible: 1,
          },
          {
            option: "Malaysian",
            selected: 0,
            visible: 1,
          },
          {
            option: "Mangalorean",
            selected: 0,
            visible: 1,
          },
          {
            option: "Meat",
            selected: 0,
            visible: 1,
          },
          {
            option: "Mediterranean",
            selected: 0,
            visible: 1,
          },
          {
            option: "Mexican",
            selected: 0,
            visible: 1,
          },
          {
            option: "Middle Eastern",
            selected: 0,
            visible: 1,
          },
          {
            option: "Mughlai",
            selected: 0,
            visible: 1,
          },
          {
            option: "Naga",
            selected: 0,
            visible: 1,
          },
          {
            option: "Nepalese",
            selected: 0,
            visible: 1,
          },
          {
            option: "North Eastern",
            selected: 0,
            visible: 1,
          },
          {
            option: "North Indian",
            selected: 0,
            visible: 1,
          },
          {
            option: "Oriental",
            selected: 0,
            visible: 1,
          },
          {
            option: "Oriya",
            selected: 0,
            visible: 1,
          },
          {
            option: "Paan",
            selected: 0,
            visible: 1,
          },
          {
            option: "Pan-Asian",
            selected: 0,
            visible: 1,
          },
          {
            option: "Pastas",
            selected: 0,
            visible: 1,
          },
          {
            option: "Persian",
            selected: 0,
            visible: 1,
          },
          {
            option: "Pizzas",
            selected: 0,
            visible: 1,
          },
          {
            option: "Portuguese",
            selected: 0,
            visible: 1,
          },
          {
            option: "Punjabi",
            selected: 0,
            visible: 1,
          },
          {
            option: "Raja",
            selected: 0,
            visible: 1,
          },
          {
            option: "Rajasthani",
            selected: 0,
            visible: 1,
          },
          {
            option: "Salads",
            selected: 0,
            visible: 1,
          },
          {
            option: "Seafood",
            selected: 0,
            visible: 1,
          },
          {
            option: "Singaporean",
            selected: 0,
            visible: 1,
          },
          {
            option: "Snacks",
            selected: 0,
            visible: 1,
          },
          {
            option: "South Indian",
            selected: 0,
            visible: 1,
          },
          {
            option: "Steakhouse",
            selected: 0,
            visible: 1,
          },
          {
            option: "Street Food",
            selected: 0,
            visible: 1,
          },
          {
            option: "Sushi",
            selected: 0,
            visible: 1,
          },
          {
            option: "Sweets",
            selected: 0,
            visible: 1,
          },
          {
            option: "Tandoor",
            selected: 0,
            visible: 1,
          },
          {
            option: "Thai",
            selected: 0,
            visible: 1,
          },
          {
            option: "Thalis",
            selected: 0,
            visible: 1,
          },
          {
            option: "Tibetan",
            selected: 0,
            visible: 1,
          },
          {
            option: "Turkish",
            selected: 0,
            visible: 1,
          },
          {
            option: "Vietnamese",
            selected: 0,
            visible: 1,
          },
          {
            option: "Waffle",
            selected: 0,
            visible: 1,
          },
        ],
        detail: "",
        heading: "Cuisines",
        applicable: 1,
        searchable: 1,
      },
      {
        type: "FilterWidget",
        title: "Show Restaurants With",
        key: "SHOW_RESTAURANTS_WITH",
        configType: "checkbox",
        visible: 1,
        options: [
          {
            option: "Offers",
            selected: 0,
            visible: 1,
          },
          {
            option: "Pure Veg",
            selected: 0,
            visible: 1,
          },
        ],
        detail: "",
        heading: "Offers & More",
        applicable: 1,
        searchable: 0,
      },
    ],
    sorts: [
      {
        type: "SortWidget",
        key: "RELEVANCE",
        title: "Relevance",
        selected: 1,
        visible: 1,
        defaultSelection: true,
      },
      {
        type: "SortWidget",
        key: "DELIVERY_TIME",
        title: "Delivery Time",
        selected: 0,
        visible: 1,
        defaultSelection: false,
      },
      {
        type: "SortWidget",
        key: "RATING",
        title: "Rating",
        selected: 0,
        visible: 1,
        defaultSelection: false,
      },
      {
        type: "SortWidget",
        key: "COST_FOR_TWO",
        title: "Cost: Low to High",
        selected: 0,
        visible: 1,
        defaultSelection: false,
      },
      {
        type: "SortWidget",
        key: "COST_FOR_TWO_H2L",
        title: "Cost: High to Low",
        selected: 0,
        visible: 1,
        defaultSelection: false,
      },
    ],
    configs: {
      ribbons: {
        PREORDER: {
          type: "PREORDER",
          text: "Preorder",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#d53d4c",
          bottomBackgroundColor: "#af2330",
          priority: 3,
        },
        EXCLUSIVE: {
          type: "EXCLUSIVE",
          text: "Exclusive",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#fa4a5b",
          bottomBackgroundColor: "#d12a3b",
          priority: 2,
        },
        NEW: {
          type: "NEW",
          text: "Newly Added",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#d53d4c",
          bottomBackgroundColor: "#af2330",
          priority: 4,
        },
        REPEAT: {
          type: "REPEAT",
          text: "Repeat",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#D53D4C",
          bottomBackgroundColor: "#B02331",
          priority: 6,
        },
        CLOUD: {
          type: "CLOUD",
          text: "Daily Menus",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#fa4a5b",
          bottomBackgroundColor: "#d12a3b",
          priority: 5,
        },
        PREMIUM: {
          type: "PREMIUM",
          text: "Premium",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#8a584b",
          bottomBackgroundColor: "#583229",
          priority: 7,
        },
        PROMOTED: {
          type: "PROMOTED",
          text: "Promoted",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#3a3c41",
          bottomBackgroundColor: "#1e2023",
          priority: 1,
        },
      },
      croutons: {
        RAIN: {
          type: "Crouton",
          bgColor: "#282C3F",
          icon: "surge_listing_piuzrv",
          textColor: "#ffffff",
          title: "Bad Weather",
          message: "${amount} extra levied on some restaurants",
        },
        SERVICEABLE_WITH_BANNER_RAIN: {
          type: "Crouton",
          bgColor: "#282C3F",
          icon: "rain_crouton_4x",
          textColor: "#ffffff",
          title: "Bad Weather",
          message: "Few restaurants unserviceable due to rains",
        },
      },
    },
    cards: [
      {
        cardType: "carousel",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "carousel",
          subtype: "topCarousel",
          data: {
            cards: [
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 635529,
                  creativeId: "rng/md/carousel/production/pneknawbadtvceqzwiep",
                  type: "restaurantCollectionV2",
                  link: "49301",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  thirdPartyVendor: "",
                  thirdPartyAddress: false,
                },
              },
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 619141,
                  creativeId: "rng/md/carousel/production/zpkkdkmvlj5cuvqbc50t",
                  type: "restaurantCollectionV2",
                  link: "56413",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  thirdPartyVendor: "",
                  thirdPartyAddress: false,
                },
              },
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 619143,
                  creativeId: "rng/md/carousel/production/lzkjv3sxwwjkzg0vxpvt",
                  type: "restaurantCollectionV2",
                  link: "56422",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  thirdPartyVendor: "",
                  thirdPartyAddress: false,
                },
              },
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 619142,
                  creativeId: "rng/md/carousel/production/tgnvusbs3fnzz7xupeno",
                  type: "restaurantCollectionV2",
                  link: "56417",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  thirdPartyVendor: "",
                  thirdPartyAddress: false,
                },
              },
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 619145,
                  creativeId: "rng/md/carousel/production/nhubtkw7dukg3ukcmpam",
                  type: "restaurantCollectionV2",
                  link: "56414",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  thirdPartyVendor: "",
                  thirdPartyAddress: false,
                },
              },
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 607188,
                  creativeId: "rng/md/carousel/production/oxe97jexxbnxqtbhg2zo",
                  type: "restaurantCollectionV2",
                  link: "11740",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  thirdPartyVendor: "",
                  thirdPartyAddress: false,
                },
              },
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 607195,
                  creativeId: "rng/md/carousel/production/ifi2lbzxeu1hvsqrsip3",
                  type: "restaurantCollectionV2",
                  link: "56421",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  thirdPartyVendor: "",
                  thirdPartyAddress: false,
                },
              },
            ],
          },
        },
        parentWidget: false,
      },
      {
        cardType: "carousel",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "carousel",
          subtype: "openFilter",
          data: {
            cards: [
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 181684,
                  creativeId: "bkhjfipzydkoqncrxpyi",
                  type: "restaurantCollectionV2",
                  link: "11718",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  title: "Offers Near You",
                  subtitle: "0 OPTIONS",
                  restaurants: [],
                  totalCount: 0,
                  dwebOpenFilterTitle: "Offers Near You",
                  dwebOpenFilterBgColor: "#FF0000",
                  dwebOpenFilterSelectIcon: "eyperwsfhaoa5vktjtu4",
                  dwebOpenFilterDeselectIcon: "urw8usdf4mk9aywd59gq",
                },
              },
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 273242,
                  creativeId: "rng/md/carousel/production/vquntqrzvkb08pe59cec",
                  type: "restaurantCollectionV2",
                  link: "46147",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  title: "Top Picks",
                  subtitle: "0 OPTIONS",
                  restaurants: [],
                  totalCount: 0,
                  dwebOpenFilterTitle: "Top Picks",
                  dwebOpenFilterBgColor: "#FF0000",
                  dwebOpenFilterSelectIcon:
                    "rng/md/carousel/production/vt13uzhjrg5r49kh9oru",
                  dwebOpenFilterDeselectIcon:
                    "rng/md/carousel/production/ser2sttildk9yt7t2s91",
                },
              },
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 181685,
                  creativeId: "auhzanqqslsq5meh0m9l",
                  type: "restaurantCollectionV2",
                  link: "11709",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  title: "Only on Swiggy",
                  subtitle: "0 OPTIONS",
                  restaurants: [],
                  totalCount: 0,
                  dwebOpenFilterTitle: "Only on Swiggy",
                  dwebOpenFilterBgColor: "#FF0000",
                  dwebOpenFilterSelectIcon: "tvjhvfzjhbxune2idler",
                  dwebOpenFilterDeselectIcon: "y4vnumwu4f8olsly1hnw",
                },
              },
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 181680,
                  creativeId: "a3jqjjod5taken7dh1bs",
                  type: "restaurantCollectionV2",
                  link: "11721",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  title: "Veg Only",
                  subtitle: "0 OPTIONS",
                  restaurants: [],
                  totalCount: 0,
                  dwebOpenFilterTitle: "Vegetarian Options",
                  dwebOpenFilterBgColor: "#FF0000",
                  dwebOpenFilterSelectIcon: "qtjc8dzfexg72lug37a0",
                  dwebOpenFilterDeselectIcon: "bm8bziikwyvwqsml1clm",
                },
              },
            ],
          },
        },
        parentWidget: false,
      },
      {
        cardType: "seeAllRestaurants",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "seeAllRestaurants",
          data: {
            title: "SEE ALL",
            totalOpenRestaurants: 1552,
            cards: [
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "105167",
                  name: "Bhartiya Jalpan",
                  uuid: "22116683-45c0-4422-af7b-36d7917a9d95",
                  city: "1",
                  area: "Commercial Street",
                  totalRatingsString: "10000+ ratings",
                  cloudinaryImageId: "lpikismf7ulkpknsbw2h",
                  cuisines: ["North Indian", "Sweets", "Desserts", "Chaat"],
                  tags: [],
                  costForTwo: 27000,
                  costForTwoString: "₹270 FOR TWO",
                  deliveryTime: 31,
                  minDeliveryTime: 31,
                  maxDeliveryTime: 31,
                  slaString: "31 MINS",
                  lastMileTravel: 3,
                  slugs: {
                    restaurant: "bhartiya-jalpan-central-bangalore",
                    city: "bangalore",
                  },
                  cityState: "1",
                  address:
                    "14, Commercial Street, Tasker Town, Shivaji Nagar, Bengaluru, Karnataka 560001",
                  locality: "Tasker Town",
                  parentId: 7518,
                  unserviceable: false,
                  veg: true,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  aggregatedDiscountInfo: {
                    header: "40% off",
                    shortDescriptionList: [
                      {
                        meta: "40% off | Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "40% off up to ₹80 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  aggregatedDiscountInfoV2: {
                    header: "40% OFF",
                    shortDescriptionList: [
                      {
                        meta: "Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "40% off up to ₹80 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  ribbon: [
                    {
                      type: "PROMOTED",
                    },
                  ],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 3400,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 3400,
                    message: "",
                    title: "Delivery Charge",
                    amount: "3400",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID:
                    "cid=6621078~p=1~eid=00000187-ffe9-a478-3bc4-eb2d0082015c",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "3 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "105167",
                    deliveryTime: 31,
                    minDeliveryTime: 31,
                    maxDeliveryTime: 31,
                    lastMileTravel: 3,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: true,
                  avgRating: "4.2",
                  totalRatings: 10000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "113657",
                  name: "Halli Donne Biryani",
                  uuid: "4a9d89ef-054d-447a-9b5d-506673592786",
                  city: "1",
                  area: "Koramangala",
                  totalRatingsString: "1000+ ratings",
                  cloudinaryImageId: "gsc5bv2hehh1mzqxvwb7",
                  cuisines: ["South Indian"],
                  tags: [],
                  costForTwo: 20000,
                  costForTwoString: "₹200 FOR TWO",
                  deliveryTime: 36,
                  minDeliveryTime: 36,
                  maxDeliveryTime: 36,
                  slaString: "36 MINS",
                  lastMileTravel: 6.400000095367432,
                  slugs: {
                    restaurant: "halli-jonne-biryani-koramangala",
                    city: "bangalore",
                  },
                  cityState: "1",
                  address:
                    "93, 17th H Main Rd, 5th Block, Koramangala, Bengaluru, Karnataka 560047",
                  locality: "5th Block",
                  parentId: 92936,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 5200,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 5200,
                    message: "",
                    title: "Delivery Charge",
                    amount: "5200",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 1,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "6.4 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "113657",
                    deliveryTime: 36,
                    minDeliveryTime: 36,
                    maxDeliveryTime: 36,
                    lastMileTravel: 6.400000095367432,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "IT_IS_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "4.0",
                  totalRatings: 1000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "459716",
                  name: "Mangalore Sea Palate",
                  uuid: "c79d2795-daf3-4eb1-bc06-8042027fdfa4",
                  city: "1",
                  area: "Jayanagar",
                  totalRatingsString: "100+ ratings",
                  cloudinaryImageId: "smx5ulmealofarwdthrv",
                  cuisines: ["Seafood", "South Indian", "Mangalorean"],
                  tags: [],
                  costForTwo: 30000,
                  costForTwoString: "₹300 FOR TWO",
                  deliveryTime: 33,
                  minDeliveryTime: 33,
                  maxDeliveryTime: 33,
                  slaString: "33 MINS",
                  lastMileTravel: 5.599999904632568,
                  slugs: {
                    restaurant: "mangalore-sea-palate-jayanagar-jayanagar",
                    city: "bangalore",
                  },
                  cityState: "1",
                  address:
                    "NO-197F,1ST FLOOR,8TH B MAIN,27TH CROSS,3RD BLOCK,JAYANAGAR,BANGALORE, Jayanagar , B.B.M.P South, Karnataka-560041",
                  locality: "3rd Block East",
                  parentId: 275607,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 4600,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 4600,
                    message: "",
                    title: "Delivery Charge",
                    amount: "4600",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 1,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "5.5 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "459716",
                    deliveryTime: 33,
                    minDeliveryTime: 33,
                    maxDeliveryTime: 33,
                    lastMileTravel: 5.599999904632568,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "IT_IS_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "4.2",
                  totalRatings: 100,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "464509",
                  name: "Leon's - Burgers & Wings (Leon Grill)",
                  uuid: "ad3d5699-2dab-4a1f-ba45-391ddd892b77",
                  city: "1",
                  area: "Frazer Town",
                  totalRatingsString: "1000+ ratings",
                  cloudinaryImageId: "qol6dzbjxyse0tylbznu",
                  cuisines: [
                    "American",
                    "Snacks",
                    "Turkish",
                    "Portuguese",
                    "Continental",
                  ],
                  tags: [],
                  costForTwo: 30000,
                  costForTwoString: "₹300 FOR TWO",
                  deliveryTime: 28,
                  minDeliveryTime: 28,
                  maxDeliveryTime: 28,
                  slaString: "28 MINS",
                  lastMileTravel: 4.199999809265137,
                  slugs: {
                    restaurant: "leon-grill-frazer-town-frazer-town-2",
                    city: "bangalore",
                  },
                  cityState: "1",
                  address:
                    "Smart Avenue, G-01, No. 90, Coles Road, Bangalore, BBMP East, Karnataka 560005",
                  locality: "Pulkeshi Nagar",
                  parentId: 371281,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  aggregatedDiscountInfo: {
                    header: "50% off",
                    shortDescriptionList: [
                      {
                        meta: "50% off | Use SPECIALS",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "50% off up to ₹100 on select items | Use code SPECIALS",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  aggregatedDiscountInfoV2: {
                    header: "50% OFF",
                    shortDescriptionList: [
                      {
                        meta: "Use SPECIALS",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "50% off up to ₹100 on select items | Use code SPECIALS",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  ribbon: [
                    {
                      type: "PROMOTED",
                    },
                  ],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 4000,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 4000,
                    message: "",
                    title: "Delivery Charge",
                    amount: "4000",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID:
                    "cid=6731921~p=16~eid=00000187-ffe9-a478-3bc4-eb3200821042",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "4.1 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "464509",
                    deliveryTime: 28,
                    minDeliveryTime: 28,
                    maxDeliveryTime: 28,
                    lastMileTravel: 4.199999809265137,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: true,
                  avgRating: "4.3",
                  totalRatings: 1000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "672387",
                  name: "Cafe Delhi Heights",
                  uuid: "50bcf794-ac21-401f-8baa-8f20deff5684",
                  city: "1",
                  area: "Central Bangalore",
                  totalRatingsString: "20+ ratings",
                  cloudinaryImageId: "6373143e852214f7a73414dc727cc975",
                  cuisines: ["Indian", "Chinese", "Italian"],
                  tags: [],
                  costForTwo: 80000,
                  costForTwoString: "₹800 FOR TWO",
                  deliveryTime: 32,
                  minDeliveryTime: 32,
                  maxDeliveryTime: 32,
                  slaString: "32 MINS",
                  lastMileTravel: 2.0999999046325684,
                  slugs: {
                    restaurant:
                      "cafe-delhi-heights-central-bangalore-central-bangalore",
                    city: "bangalore",
                  },
                  cityState: "1",
                  address:
                    "Cafe Delhi Heights FORUM REX WALK, Bangalore North, Bangalore Urban, Karnataka, 560001 FORUM REX WALK, Bangalore North, Bangalore Urban, Karnataka, 560001",
                  locality: "Forum Rex Walk",
                  parentId: 5408,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 2800,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 2800,
                    message: "",
                    title: "Delivery Charge",
                    amount: "2800",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "2 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "672387",
                    deliveryTime: 32,
                    minDeliveryTime: 32,
                    maxDeliveryTime: 32,
                    lastMileTravel: 2.0999999046325684,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "4.3",
                  totalRatings: 20,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "80517",
                  name: "Savoury Restaurant",
                  uuid: "75fd0f34-da99-457f-b8ec-f6c9dcc6bc4c",
                  city: "1",
                  area: "Frazer Town",
                  totalRatingsString: "10000+ ratings",
                  cloudinaryImageId: "6b38d5679a48a299242c364df3975f2f",
                  cuisines: [
                    "Arabian",
                    "Indian",
                    "Chinese",
                    "Tandoor",
                    "Biryani",
                    "Seafood",
                    "Kerala",
                  ],
                  tags: [],
                  costForTwo: 60000,
                  costForTwoString: "₹600 FOR TWO",
                  deliveryTime: 32,
                  minDeliveryTime: 32,
                  maxDeliveryTime: 32,
                  slaString: "32 MINS",
                  lastMileTravel: 4.900000095367432,
                  slugs: {
                    restaurant: "savoury-restaurant-frazer-town-frazer-town",
                    city: "bangalore",
                  },
                  cityState: "1",
                  address:
                    "No:27, Mosque Road, Frazer town, Bangalore - 560005",
                  locality: "Mosque Road",
                  parentId: 179209,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  aggregatedDiscountInfo: {
                    header: "30% off",
                    shortDescriptionList: [
                      {
                        meta: "30% off | Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "30% off up to ₹75 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  aggregatedDiscountInfoV2: {
                    header: "30% OFF",
                    shortDescriptionList: [
                      {
                        meta: "Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "30% off up to ₹75 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 4000,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 4000,
                    message: "",
                    title: "Delivery Charge",
                    amount: "4000",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 1,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "4.9 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "80517",
                    deliveryTime: 32,
                    minDeliveryTime: 32,
                    maxDeliveryTime: 32,
                    lastMileTravel: 4.900000095367432,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "IT_IS_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "4.3",
                  totalRatings: 10000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "574263",
                  name: "Rahhams",
                  uuid: "9ddbdf8d-e73c-4a33-81f2-3713c4193b39",
                  city: "1",
                  area: "Frazer Town",
                  totalRatingsString: "1000+ ratings",
                  cloudinaryImageId: "edkut9gmhjqq6urnnmwv",
                  cuisines: [
                    "Biryani",
                    "Mughlai",
                    "North Indian",
                    "Kebabs",
                    "Chinese",
                    "Seafood",
                    "Beverages",
                  ],
                  tags: [],
                  costForTwo: 70000,
                  costForTwoString: "₹700 FOR TWO",
                  deliveryTime: 30,
                  minDeliveryTime: 30,
                  maxDeliveryTime: 30,
                  slaString: "30 MINS",
                  lastMileTravel: 4.599999904632568,
                  slugs: {
                    restaurant: "rahhams-frazer-town-frazer-town-2",
                    city: "bangalore",
                  },
                  cityState: "1",
                  address:
                    "82, Maiganda Deva Mudaliar Rd, Pulikeshi Nagar, Bengaluru, Karnataka 560005, India",
                  locality: "Pulikeshi Nagar",
                  parentId: 2534,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  ribbon: [
                    {
                      type: "PROMOTED",
                    },
                  ],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 4000,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 4000,
                    message: "",
                    title: "Delivery Charge",
                    amount: "4000",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID:
                    "cid=6730233~p=7~eid=00000187-ffe9-a478-3bc4-eb2f00820713",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "4.5 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "574263",
                    deliveryTime: 30,
                    minDeliveryTime: 30,
                    maxDeliveryTime: 30,
                    lastMileTravel: 4.599999904632568,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: true,
                  avgRating: "4.3",
                  totalRatings: 1000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "626483",
                  name: "Andhra Ruchulu",
                  uuid: "1644fb77-01a9-4e1e-a548-071a541bdb3b",
                  city: "1",
                  area: "The President Hotel",
                  totalRatingsString: "100+ ratings",
                  cloudinaryImageId: "b3db7e8c7690d74188ae0999eae30955",
                  cuisines: ["Chinese", "North Indian", "Biryani", "Snacks"],
                  tags: [],
                  costForTwo: 50000,
                  costForTwoString: "₹500 FOR TWO",
                  deliveryTime: 33,
                  minDeliveryTime: 33,
                  maxDeliveryTime: 33,
                  slaString: "33 MINS",
                  lastMileTravel: 4.199999809265137,
                  slugs: {
                    restaurant: "andhra-ruchulu-malleshwaram-malleshwaram",
                    city: "bangalore",
                  },
                  cityState: "1",
                  address:
                    "101, Railway Parallel Road, Kumara Park West, Bangalore -560020",
                  locality: "Sankey Road",
                  parentId: 3789,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  aggregatedDiscountInfo: {
                    header: "Free Payasam",
                    shortDescriptionList: [
                      {
                        meta: "Free Payasam on orders above ₹930",
                        discountType: "Freebie",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "Free Payasam on orders above ₹930",
                        discountType: "Freebie",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  aggregatedDiscountInfoV2: {
                    header: "",
                    shortDescriptionList: [
                      {
                        meta: "Free Payasam",
                        discountType: "Freebie",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "Free Payasam on orders above ₹930",
                        discountType: "Freebie",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 4000,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 4000,
                    message: "",
                    title: "Delivery Charge",
                    amount: "4000",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 1,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "4.1 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "626483",
                    deliveryTime: 33,
                    minDeliveryTime: 33,
                    maxDeliveryTime: 33,
                    lastMileTravel: 4.199999809265137,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "IT_IS_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "4.1",
                  totalRatings: 100,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "435405",
                  name: "Chaayos Chai+Snacks=Relax",
                  uuid: "83f35f21-d3c1-42d1-847a-7fe2d1567f15",
                  city: "1",
                  area: "Cunningham Road",
                  totalRatingsString: "500+ ratings",
                  cloudinaryImageId: "0a6f66d75eb042123e34d89bef7189ce",
                  cuisines: [
                    "Bakery",
                    "Beverages",
                    "Chaat",
                    "Desserts",
                    "Home Food",
                    "Italian",
                    "Maharashtrian",
                    "Snacks",
                    "Street Food",
                    "Sweets",
                  ],
                  tags: [],
                  costForTwo: 25000,
                  costForTwoString: "₹250 FOR TWO",
                  deliveryTime: 36,
                  minDeliveryTime: 36,
                  maxDeliveryTime: 36,
                  slaString: "36 MINS",
                  lastMileTravel: 3,
                  slugs: {
                    restaurant:
                      "chaayos-meri-wali-chai-cunningham-road-central-bangalore",
                    city: "bangalore",
                  },
                  cityState: "1",
                  address:
                    "Shop No. 15, 22, 23 and 24, Ground Floor, Unit No. 02, HM Geneva House, #14 Cunningham Road, Vasanth Nagar, Shivajinagara, B.B.M.P East, Karnataka-560052",
                  locality: "Vasanth Nagar",
                  parentId: 281782,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  aggregatedDiscountInfo: {
                    header: "50% off",
                    shortDescriptionList: [
                      {
                        meta: "50% off | Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "50% off up to ₹100 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  aggregatedDiscountInfoV2: {
                    header: "50% OFF",
                    shortDescriptionList: [
                      {
                        meta: "Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "50% off up to ₹100 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 3400,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 3400,
                    message: "",
                    title: "Delivery Charge",
                    amount: "3400",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "3 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "435405",
                    deliveryTime: 36,
                    minDeliveryTime: 36,
                    maxDeliveryTime: 36,
                    lastMileTravel: 3,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "4.4",
                  totalRatings: 500,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "382471",
                  name: "Andhra Gunpowder",
                  uuid: "854ec3d1-a6d8-4eca-b7ea-c3d979263d44",
                  city: "1",
                  area: "Frazer Town",
                  totalRatingsString: "1000+ ratings",
                  cloudinaryImageId: "ogef9xssra7f4kaxe7ox",
                  cuisines: ["Andhra", "Biryani", "South Indian"],
                  tags: [],
                  costForTwo: 35000,
                  costForTwoString: "₹350 FOR TWO",
                  deliveryTime: 30,
                  minDeliveryTime: 30,
                  maxDeliveryTime: 30,
                  slaString: "30 MINS",
                  lastMileTravel: 4.5,
                  slugs: {
                    restaurant: "andhra-gunpowder-frazer-town-frazer-town",
                    city: "bangalore",
                  },
                  cityState: "1",
                  address:
                    "60/1, 1st Floor Close Rd, Cleveland Town, Pulikeshi Nagar, Sherlock's Pub Building, Bengaluru, Karnataka 560005",
                  locality: "Pulikeshi Nagar",
                  parentId: 10496,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  aggregatedDiscountInfo: {
                    header: "40% off",
                    shortDescriptionList: [
                      {
                        meta: "40% off | Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "40% off up to ₹80 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  aggregatedDiscountInfoV2: {
                    header: "40% OFF",
                    shortDescriptionList: [
                      {
                        meta: "Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "40% off up to ₹80 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  ribbon: [
                    {
                      type: "PROMOTED",
                    },
                  ],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 4000,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 4000,
                    message: "",
                    title: "Delivery Charge",
                    amount: "4000",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID:
                    "cid=6709619~p=10~eid=00000187-ffe9-a478-3bc4-eb3000820a51",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "4.5 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "382471",
                    deliveryTime: 30,
                    minDeliveryTime: 30,
                    maxDeliveryTime: 30,
                    lastMileTravel: 4.5,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: true,
                  avgRating: "4.3",
                  totalRatings: 1000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "409452",
                  name: "MYK BOX",
                  uuid: "51d08d78-e6ee-4664-9745-df9271388454",
                  city: "1",
                  area: "Tavarekere",
                  totalRatingsString: "Too Few Ratings",
                  cloudinaryImageId: "oxwm7la0zir49jbrfbm8",
                  cuisines: ["Chinese", "Oriental"],
                  tags: [],
                  costForTwo: 30000,
                  costForTwoString: "₹300 FOR TWO",
                  deliveryTime: 37,
                  minDeliveryTime: 37,
                  maxDeliveryTime: 37,
                  slaString: "37 MINS",
                  lastMileTravel: 6.5,
                  slugs: {
                    restaurant: "myk-box-btm-btm",
                    city: "bangalore",
                  },
                  cityState: "1",
                  address:
                    "NO-80/10-2,1ST MAIN ROAD,TAVAREKERE MAIN ROAD,CHIKKA ADUGUDI,BANGALORE, 560029",
                  locality: "Chikka Adugudi",
                  parentId: 251305,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 5200,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 5200,
                    message: "",
                    title: "Delivery Charge",
                    amount: "5200",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 1,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "6.5 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "409452",
                    deliveryTime: 37,
                    minDeliveryTime: 37,
                    maxDeliveryTime: 37,
                    lastMileTravel: 6.5,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "IT_IS_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "--",
                  totalRatings: 0,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "69876",
                  name: "Subway",
                  uuid: "d1a0e6e6-575c-4453-9f78-d298026b0e64",
                  city: "1",
                  area: "Ashok Nagar",
                  totalRatingsString: "1000+ ratings",
                  cloudinaryImageId: "0bf19a82b109b40c2f5c56d00f071a33",
                  cuisines: [
                    "Fast Food",
                    "Salads",
                    "Snacks",
                    "Desserts",
                    "Beverages",
                  ],
                  tags: [],
                  costForTwo: 35000,
                  costForTwoString: "₹350 FOR TWO",
                  deliveryTime: 24,
                  minDeliveryTime: 24,
                  maxDeliveryTime: 24,
                  slaString: "24 MINS",
                  lastMileTravel: 0.6000000238418579,
                  slugs: {
                    restaurant: "subway-central-bangalore1-central-bangalore",
                    city: "bangalore",
                  },
                  cityState: "1",
                  address: "Ubcity 2nd level Vital mallya Road Bangalore",
                  locality: "UB City",
                  parentId: 2,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  aggregatedDiscountInfo: {
                    header: "30% off",
                    shortDescriptionList: [
                      {
                        meta: "30% off | Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "30% off up to ₹75 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  aggregatedDiscountInfoV2: {
                    header: "30% OFF",
                    shortDescriptionList: [
                      {
                        meta: "Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "30% off up to ₹75 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 2800,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 2800,
                    message: "",
                    title: "Delivery Charge",
                    amount: "2800",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "0.6 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "69876",
                    deliveryTime: 24,
                    minDeliveryTime: 24,
                    maxDeliveryTime: 24,
                    lastMileTravel: 0.6000000238418579,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "4.2",
                  totalRatings: 1000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "667962",
                  name: "Paris Panini - Gourmet Sandwiches",
                  uuid: "f259a8ff-15e1-4584-a714-4ec867531d87",
                  city: "1",
                  area: "Central Bangalore",
                  totalRatingsString: "100+ ratings",
                  cloudinaryImageId: "33101e2fff3a071cbd8b85e73c0d4f45",
                  cuisines: [
                    "Snacks",
                    "European",
                    "Salads",
                    "Beverages",
                    "Pastas",
                  ],
                  tags: [],
                  costForTwo: 50000,
                  costForTwoString: "₹500 FOR TWO",
                  deliveryTime: 25,
                  minDeliveryTime: 25,
                  maxDeliveryTime: 25,
                  slaString: "25 MINS",
                  lastMileTravel: 1.7999999523162842,
                  slugs: {
                    restaurant:
                      "paris-panini-–-gourmet-sandwiches-central-bangalore-central-bangalore",
                    city: "bangalore",
                  },
                  cityState: "1",
                  address: "NO 20, CHURCH STREET, BANGALORE,560001",
                  locality: "Church Street",
                  parentId: 21019,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  aggregatedDiscountInfo: {
                    header: "30% off",
                    shortDescriptionList: [
                      {
                        meta: "30% off | Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "30% off up to ₹75 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  aggregatedDiscountInfoV2: {
                    header: "30% OFF",
                    shortDescriptionList: [
                      {
                        meta: "Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "30% off up to ₹75 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  ribbon: [
                    {
                      type: "PROMOTED",
                    },
                  ],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 2800,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 2800,
                    message: "",
                    title: "Delivery Charge",
                    amount: "2800",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID:
                    "cid=6576699~p=13~eid=00000187-ffe9-a478-3bc4-eb3100820d31",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "1.7 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "667962",
                    deliveryTime: 25,
                    minDeliveryTime: 25,
                    maxDeliveryTime: 25,
                    lastMileTravel: 1.7999999523162842,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: true,
                  avgRating: "4.5",
                  totalRatings: 100,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "516829",
                  name: "VASAVI ANDHRA MESS",
                  uuid: "cc6e60a7-c2b9-4a23-9100-2b7a04f73cc1",
                  city: "1",
                  area: "Malleshwaram",
                  totalRatingsString: "100+ ratings",
                  cloudinaryImageId: "ivdse6ilbfpczq1qxgcn",
                  cuisines: ["South Indian", "Andhra", "Chinese"],
                  tags: [],
                  costForTwo: 20000,
                  costForTwoString: "₹200 FOR TWO",
                  deliveryTime: 38,
                  minDeliveryTime: 38,
                  maxDeliveryTime: 38,
                  slaString: "38 MINS",
                  lastMileTravel: 6,
                  slugs: {
                    restaurant: "vasavi-andhra-mess-malleshwaram-malleshwaram",
                    city: "bangalore",
                  },
                  cityState: "1",
                  address:
                    "W Park Rd, Malleswaram, Bengaluru, Karnataka 560003, India",
                  locality: "W Park Road",
                  parentId: 308724,
                  unserviceable: false,
                  veg: true,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 5200,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 5200,
                    message: "",
                    title: "Delivery Charge",
                    amount: "5200",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 1,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "6 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "516829",
                    deliveryTime: 38,
                    minDeliveryTime: 38,
                    maxDeliveryTime: 38,
                    lastMileTravel: 6,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "IT_IS_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "3.7",
                  totalRatings: 100,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "637141",
                  name: "The Home Bakery",
                  uuid: "4885cb81-ca9f-44ee-a4aa-534dfe7fe784",
                  city: "1",
                  area: "Frazer Town",
                  totalRatingsString: "20+ ratings",
                  cloudinaryImageId: "igyqxtmnvpnbtdisfi0e",
                  cuisines: ["Bakery", "Desserts"],
                  tags: [],
                  costForTwo: 20000,
                  costForTwoString: "₹200 FOR TWO",
                  deliveryTime: 27,
                  minDeliveryTime: 27,
                  maxDeliveryTime: 27,
                  slaString: "27 MINS",
                  lastMileTravel: 4.699999809265137,
                  slugs: {
                    restaurant: "the-home-bakery-frazer-town-frazer-town",
                    city: "bangalore",
                  },
                  cityState: "1",
                  address:
                    "5/1, L1-05 Ground Floor, Assaye Rd, Halasuru, Sindhi Colony, Pulikeshi Nagar, Bengaluru, Karnataka 560042, India",
                  locality: "Assaye Rd",
                  parentId: 209607,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  aggregatedDiscountInfo: {
                    header: "40% off",
                    shortDescriptionList: [
                      {
                        meta: "40% off | Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "40% off up to ₹80 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  aggregatedDiscountInfoV2: {
                    header: "40% OFF",
                    shortDescriptionList: [
                      {
                        meta: "Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "40% off up to ₹80 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 4000,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 4000,
                    message: "",
                    title: "Delivery Charge",
                    amount: "4000",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 1,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "4.6 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "637141",
                    deliveryTime: 27,
                    minDeliveryTime: 27,
                    maxDeliveryTime: 27,
                    lastMileTravel: 4.699999809265137,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "IT_IS_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "4.4",
                  totalRatings: 20,
                  new: false,
                },
                subtype: "basic",
              },
            ],
            totalRestaurants: 1552,
          },
          subtype: "personalized",
        },
        parentWidget: false,
      },
    ],
    nextPageFetch: 0,
  },
  tid: "8661bf78-9066-4634-ba17-72b7354e59e5",
  sid: "6yf97a51-5a02-4c7c-9161-2b48a4be0259",
  deviceId: "4edade31-105d-9652-0907-dbef412759fa",
  csrfToken: "1xGLUarG9UUF-sui1XW3yTZLP6Cg9EKdsJV8aUYY",
};
export default apiData;
